language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.2
          env: COMPOSER_PROJECT=true

install:
    - composer install
    - if [[ $COMPOSER_PROJECT != "" ]]; then composer create-project nette/coding-standard:dev-master temp/nette-coding-standard; fi

script:
    - ./ecs check examples --preset php56
    - ./ecs check examples --preset php70
    - ./ecs check examples --preset php71
    - if [[ $COMPOSER_PROJECT != "" ]]; then temp/nette-coding-standard/ecs check examples --preset php71; fi

notifications:
    email: false

dist: xenial

cache:
    directories:
        - $HOME/.composer/cache
